jobs:
  - name: speedtest
    command: /config/speedtest2mqtt.sh
    shell: /bin/bash
    schedule: "*/5 * * * *"
    env_file: /config/container.env
    captureStderr: false
    captureStdout: true
    concurrencyPolicy: Forbid
