name: Anchore actions

on:
  schedule:
    - cron:  '0 0 * * SUN'
  #push:
  #  branches: [ "main" ]
  #  tags: [ 'v*.*.*' ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  anchore-build-scan:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      attestations: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2
      - name: Build the Docker image
        run: docker build --file Dockerfile --tag localbuild/testimage:latest --build-arg TARGETARCH=amd64 .
      - name: Run Anchore Scan
        uses: anchore/scan-action@v6.1.0
        id: scan
        with:
          image: localbuild/testimage:latest
          fail-build: false
          output-format: sarif
#          output-file: "/home/runner/work/speedtest2mqtt/speedtest2mqtt/results/actions.sarif"
          severity-cutoff: medium
          only-fixed: false
          add-cpes-if-none: false
          by-cve: false
          vex: false
          cache-db: false
#      - name: Upload Anchore Scan Report
#        uses: github/codeql-action/upload-sarif@v3.28.10
#        with:
#          sarif_file: ${{ steps.scan.outputs.sarif }}
