name: Automerge Pull Request

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
#    inputs:
#      logLevel:
#        description: 'Log level'
#        required: true
#        default: 'warning'
#        type: choice
#        options:
#        - info
#        - warning
#        - debug
#      tags:
#        description: 'Test Anchore Grype Vulnerability scan'
#        required: false
#        type: boolean
#      environment:
#        description: 'Environment to run tests against'
#        type: environment
#        required: true
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
        with:
          target: minor
          github-token: ${{ secrets.AUTOMERGE_TOKEN }}
